### ISSUE TITLE
workspace does not support non-json based configurations

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-workspace#377]
### Bug or feature request
- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)
loopback-boot (http://apidocs.strongloop.com/loopback-boot/) supports the feature of passing in an object rather than a string - this allows you to define things like datasources from data which could be obtained from any source, rather than a static.json file

The problem comes when trying to use any of the `slc loopback:xx` features, as the generator-loopback lib uses workspaces, which simply assumes that everything is static, as it does `boot(app, __dirname);`

It even goes so far as writing out json files *even when you don't want it to* ! For example, workspace.js has this code

```
    Workspace.loadWorkspace = function(path, cb) {
      app.dataSources.db.connector.saveToFile(null, function() {
```
so this will create a datasources.json file in my server directory , with no warning or apologies ;)

**Comment by bajtos** [comment]
I think there are two parts in play here:

 1. loopback-workspace/`slc loopback:xxx` does not support custom project layouts, like the one described above.
 2. loopback-workspace is creating redundant empty files (e.g. a new `server/datasources.json` that is not used by the app because `boot` is configured differently).

While implementing support for (1) may be ideal, I think it will require way too much work, and it may be impossible to implement without having to run `server/server.js` to figure out how exactly the app is booted. I'd rather not go down this route.

I think we should fix (2) and improve loopback-workspace to not (re)create unrelated files that may have been deleted by the user. For example, when running `slc loopback:remote-method`, this command should touch only the model JSON file and nothing else.

This is not possible in the current design (loopback-workspace@3). @deepakrkris and @ritch are working on a new implementation for loopback-workspace@4, I think it makes a lot of sense to design the new implementation in such way that each change writes only the affected files and nothing else.

**Comment by jmls** [comment]
I'm not sure that I agree with you on #1 : There must be any number of projects that either create dynamic models or datasources etc - and this design makes it impossible to use any of the slc utilities

If you were to change workspaces  use server/server for all instances, then surely it would cover the existing structures (ie the default) and the dynamic structure (and this is **not** a custom project layout - it's one that's documented and supported by strongloop)

**Comment by bajtos** [comment]
@jmls hmm, perhaps my understanding of a "dynamic structure" is different from what do you mean. Could you please create a sample loopback project per our [Bug report instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report) to show what exactly you would like to get supported.

**Comment by jmls** [comment]
A simple sample project is here : https://github.com/jmls/lb-dynamic-ws

this project adds a config object to create datasources, rather than a static datasources.json file. 

The project was created with `slc loopback` and certain static .json files were then removed. The server/server.js file was then modified to define a config object which was passed to boot instead of __dirname, according to the boot docs  (http://apidocs.strongloop.com/loopback-boot/) 

However, when you run `slc loopback:model` you get the warning 

`Warning: Found no data sources to attach model. There will be no data-access methods available until datasources are attached.`

**Comment by jmls** [comment]
Actually, I think that I've just unearthed another bug. If you modify `server/server.js` to say 

```
// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, config, function(err) {

  Object.keys(app.dataSources).forEach((key) => {
    console.log(app.dataSources[key].settings.name)
  })

  if (err) throw err;

  // start the server if `$ node server.js`
  if (require.main === module)
    app.start();
});
```

you get 4 dataSources : 2 ds1 and 2 ds2

Looks like something is creating the dataSource twice

**Comment by bajtos** [comment]
> Actually, I think that I've just unearthed another bug.

This would be a bug in loopback-boot, please open an issue in https://github.com/strongloop/loopback-boot/issues and include information about the version of loopback-boot you are using.

> A simple sample project is here : https://github.com/jmls/lb-dynamic-ws

Great!

Your project shows what I had in mind when discussing "dynamic structure". Because the boot instructions are created by javascript code, it's difficult for loopback-workspace to support such projects, unless we 
 1. load the app with monkey-patched loopback-boot, so that `boot(app, options, cb)` does not start the app, but send the boot config back to workspace; or
 2. write a javascript parser/interpreter that can understand possibly arbitrarily complex javascript code that eventually calls `boot(app, options, cb)`.

IMO, neither option is worth the effort.

Having wrote that, it's entirely possible that I am missing some other solution that is easy to write and maintain. Feel free to propose it!

**Comment by jmls** [comment]
I think there's a middle way - by convention - it should be possible to create a folder / file called **dynamic** in the server folder. If such a file exists, It is the responsibility of this program to return an appropriate config object

loopback-workspaces can check for the existence of this file, call it if it exists, and then call boot() with the config, or call boot() with __dirname if the file does not exist or does not return an object

I will see if I can put something together

**Comment by bajtos** [comment]
> I think there's a middle way - by convention - it should be possible to create a folder / file called dynamic in the server folder. If such a file exists, It is the responsibility of this program to return an appropriate config object

Interesting, that may work. I think we will need the "dynamic" configurator to also tell us which parts are dynamic and thus cannot be modified using loopback-workspace/`slc` tooling.

> loopback-workspaces can check for the existence of this file, call it if it exists, and then call boot() with the config, or call boot() with __dirname if the file does not exist or does not return an object

In most cases, loopback-workspace does not load the project and does not call `boot()` at all. This is intentional and important, otherwise loopback-workspace breaks when the app cannot be loaded, e.g. because a connector was not installed from npm yet or there is a bug in custom javascript code (model, boot script, etc).

We have already had bad experience with the few places where we are trying to load the app, most notably when testing whether a datasource can connect to the configured database. Any error in the app code will cause these checks to fail with unrelated errors, which is difficult to explain to users.

**Comment by jmls** [comment]
Indeed - that's why I would propose that the configurator's only purpose would be to return a config file : not to boot the app, or try to load it. 

The server/server app itself should call this configurator before boot as well.

As long as you have the config , you don't **need** to boot , just use the appropriate key. So instead of reading in `datasources.json`, use the `datasources` key in the config

So where you _are_ booting, use the config. Otherwise use the config keys

**Comment by jmls** [comment]
@bajtos : could you point me in the direction where DataSourceDefinitions are manipulated ? I have modifed the code so that it can boot with a config if supplied, and whilst I am able to load all of the models (ConfigFile etc) when it comes to calling `actions.loadDataSource` the `workspace.models.DataSourceDefinition.find()` does not find any records

running with `DEBUG=loopback:data` I see 

```
loopback:datasource Settings: {"defaultForType":"db","debug":true} +0ms
loopback:datasource Settings: {"name":"mem","debug":true} +1s
loopback:datasource Settings: {"name":"db","debug":true} +3ms
```
so there are some ds loaded

I've been trawling the codebase, but can't find anywhere obvious where the `DataSourceDefinition` records are being created. In this case, I suspect that they are being loaded from the normal `datasources.json` file, rather than looping through the app.dataSources object - and as I am trying to load the config dynamically, I don't have such a file - so it borks out and says that there are no dataSources

**Comment by bajtos** [comment]
In general, [server/connector.js](https://github.com/strongloop/loopback-workspace/blob/4653142725834b664ffc26ed50bc782c967d01d2/server/connector.js) is the place where to start looking for any load/save related implementation.

The next place to look at is [Facet.loadIntoCache](https://github.com/strongloop/loopback-workspace/blob/4653142725834b664ffc26ed50bc782c967d01d2/server/connector.js#L141). Facets represents `common` and `server` subdirectories (and `client`, but that one is not really supported yet).

Datasources are loaded by this code: [common/models/facet.js#L156-L173](https://github.com/strongloop/loopback-workspace/blob/4653142725834b664ffc26ed50bc782c967d01d2/common/models/facet.js#L156-L173)

**Comment by bajtos** [comment]
@jmls ping, what's the status of your work? I am revisiting old stale issues, this one looks like a candidate for closing to me. Thoughts?
