### ISSUE TITLE
Upgrade workspace from LB2 to LB3

### ISSUE THREAD

**Issue by asaf050** [strongloop/loopback-workspace#498]
# Description/Steps to reproduce
npm i loopback-workspace

# Expected result
install loopback 3 as a dependency

# Additional information
installing loopback 2 instead

# Acceptance Criteria
- [ ] Follow the [migration guide](https://loopback.io/doc/en/lb3/Migrating-to-3.0.html) to update the LoopBack workspace to use LB3.

**Comment by ryan-open** [comment]
@dhmlau @bajtos Is this intended?

**Comment by dhmlau** [comment]
Thanks for pinging.  No, it's not intended.  With LB will be EOL in April 2019, we should update this. 


Framework | Status | Published | EOL | Runtime | GA | EOL
-- | -- | -- | -- | -- | -- | --
LoopBack 4 | Current | Oct 2018 | Apr 2021(minimum) | Node 10 | Oct 2018 | Apr 2021
Loopback 3 | Active LTS | Dec 2016 | Dec 2019 | Node 8 | Oct 2017 | Dec 2019
Loopback 2 | Maintenance LTS | Jul 2014 | Apr 2019 | Node 6 | Oct 2016 | Apr 2019

I'm reopening this issue.  See if we can make it to Nov (perhaps as stretch goal because currently our Nov sprint is pretty full) or Dec.

**Comment by dhmlau** [comment]
Besides updating to use `loopback@3` by default, I think there are multiple places that should be updated as well.  According to @bajtos, this could be breaking change, so we might as well take this chance to update.

- [ ] update to use `loopback@3` by default
- [ ] Other things to consider
   - [ ] update dependencies of this module, e.g. `strong-globalize` 
   - [ ] update the `engines` in the template to use Node 6+ https://github.com/strongloop/loopback-workspace/blob/master/templates/projects/empty-server/data.js#L17
 

@nabdelgadir, could you please work with @jannyHou to get this task groomed?  Thanks!
